name: Android
        
on:
  workflow_dispatch:
  push:   
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs: 
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macos-13", "ubuntu-24.04"]
        #apply-patch: ["true", "false"]
        apply-patch: ["true"]
        android-api-level: [29, 30, 31, 32, 33, 34, 35]
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    #- name: Run Local Tests on ${{ matrix.os }}
    #  run: swift test
    - name: Apply Patches
      if: ${{ matrix.apply-patch == 'true' }}
      run: |
        curl -fsSL https://raw.githubusercontent.com/finagolfin/swift-android-sdk/refs/heads/main/swift-nio-disable-ecn-tests.patch | git apply
        curl -fsSL https://raw.githubusercontent.com/finagolfin/swift-android-sdk/refs/heads/main/swift-nio-filesystem.patch | git apply
    - name: Run Android Emulator Tests
      uses: skiptools/swift-android-action@v2
      with:
        android-api-level: ${{ matrix.android-api-level }}


